// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID         int64
	CustomerID int64
	CreatedAt  pgtype.Timestamptz
}

type OrderItem struct {
	ID             int64
	OrderID        int64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Quantity       int32
	PriceInCenters int32
	ProductID      int64
}

type Product struct {
	ID             int64
	Name           string
	PriceInCenters int32
	Description    pgtype.Text
	Quantity       int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
