// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, price_in_centers, description, quantity, created_at, updated_at FROM products WHERE id=$1
`

func (q *Queries) GetProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCenters,
		&i.Description,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, price_in_centers, description, quantity, created_at, updated_at FROM products
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCenters,
			&i.Description,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postOrder = `-- name: PostOrder :one
INSERT INTO order_items(order_id, quantity,price_in_centers,product_id) VALUES($1, $2, $3, $4) RETURNING id, order_id, created_at, updated_at, quantity, price_in_centers, product_id
`

type PostOrderParams struct {
	OrderID        int64
	Quantity       int32
	PriceInCenters int32
	ProductID      int64
}

func (q *Queries) PostOrder(ctx context.Context, arg PostOrderParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, postOrder,
		arg.OrderID,
		arg.Quantity,
		arg.PriceInCenters,
		arg.ProductID,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Quantity,
		&i.PriceInCenters,
		&i.ProductID,
	)
	return i, err
}
