// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	GetProductByID(ctx context.Context, id int64) (Product, error)
	ListProducts(ctx context.Context) ([]Product, error)
	createOrder(ctx context.Context, arg createOrderParams) (Order, error)
	createOrderItem(ctx context.Context, arg createOrderItemParams) (OrderItem, error)
}

var _ Querier = (*Queries)(nil)
