// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	GetProductByID(ctx context.Context, id int64) (Product, error)
	ListProducts(ctx context.Context) ([]Product, error)
	PostOrder(ctx context.Context, arg PostOrderParams) (OrderItem, error)
}

var _ Querier = (*Queries)(nil)
